In [1]:
# Install packages into the notebook's current Python environment
%pip install pandas numpy scikit-learn xgboost -q

# Imports
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from xgboost import XGBClassifier


# ----------------------------
# LOAD DATA
# ----------------------------

df = pd.read_csv(r"D:\uni\Year 3\Dataengineering\WeatherAUS-master\WeatherAUS\data\weatherAUS_cleaned.csv")

print("Dataset shape:", df.shape)


# ----------------------------
# FEATURES AND TARGET
# ----------------------------

x = df.drop("RainTomorrow", axis=1)
y = df["RainTomorrow"]

print("Features:", x.shape)
print("Target:", y.shape)


# ----------------------------
# TRAIN / TEST SPLIT
# ----------------------------

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining set:", x_train.shape)
print("Testing set:", x_test.shape)


# ==========================================================
# RANDOM FOREST
# ==========================================================

rf_model = RandomForestClassifier(
    n_estimators=800,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

rf_model.fit(x_train, y_train)

rf_predictions = rf_model.predict(x_test)

print("\n================ RANDOM FOREST ================\n")

print("Accuracy:", accuracy_score(y_test, rf_predictions))

print("\nClassification Report:")
print(classification_report(y_test, rf_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))


# ==========================================================
# XGBOOST
# ==========================================================

xgb_model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    random_state=42,
    n_jobs=-1,
    eval_metric="logloss"
)

xgb_model.fit(x_train, y_train)

xgb_predictions = xgb_model.predict(x_test)

print("\n================ XGBOOST ================\n")

print("Accuracy:", accuracy_score(y_test, xgb_predictions))

print("\nClassification Report:")
print(classification_report(y_test, xgb_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_predictions))

Note: you may need to restart the kernel to use updated packages.
Dataset shape: (142193, 76)
Features: (142193, 75)
Target: (142193,)

Training set: (113754, 75)
Testing set: (28439, 75)

================ RANDOM FOREST ================

Accuracy: 0.8534758606139456

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.91      0.91     22064
           1       0.67      0.67      0.67      6375

    accuracy                           0.85     28439
   macro avg       0.79      0.79      0.79     28439
weighted avg       0.85      0.85      0.85     28439


Confusion Matrix:
[[20012  2052]
 [ 2115  4260]]

================ XGBOOST ================

Accuracy: 0.8623017686979149

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.95      0.91     22064
           1       0.77      0.56      0.64      6375

    accuracy                           0.86     28439
   macro avg     

In [2]:
xgb_model = XGBClassifier(
    n_estimators=5000,
    learning_rate=1,
    max_depth=10,
    scale_pos_weight=3.65,
    random_state=42,
    n_jobs=-1,
    eval_metric="logloss"
)

xgb_model.fit(x_train, y_train)

xgb_predictions = xgb_model.predict(x_test)

print("Accuracy:", accuracy_score(y_test, xgb_predictions))

print("\nClassification Report:")
print(classification_report(y_test, xgb_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_predictions))

Accuracy: 0.8574492774007525

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.92      0.91     22064
           1       0.70      0.63      0.66      6375

    accuracy                           0.86     28439
   macro avg       0.80      0.78      0.79     28439
weighted avg       0.85      0.86      0.85     28439


Confusion Matrix:
[[20369  1695]
 [ 2359  4016]]


In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

lr_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ))
])

lr_model.fit(x_train, y_train)

lr_predictions = lr_model.predict(x_test)

print("Accuracy:", accuracy_score(y_test, lr_predictions))

print("\nClassification Report:")
print(classification_report(y_test, lr_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, lr_predictions))

Accuracy: 0.7940855866943282

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.80      0.86     22064
           1       0.53      0.78      0.63      6375

    accuracy                           0.79     28439
   macro avg       0.73      0.79      0.74     28439
weighted avg       0.84      0.79      0.81     28439


Confusion Matrix:
[[17623  4441]
 [ 1415  4960]]
